
POST http://localhost:5000/hires
Content-Type: application/json

{
    "name": "Abdulrahman Abdi",
    "email": "abdulrahmanaabdi98@gmail.com",
    "job_title": "developer",
    "department": "cyber security",
    "hiring_manager": "faltu",
    "hm_email": "chelseafc110698@gmail.com"
}

